### ISSUE TITLE
Propose More Readable Panel Route and Data

### ISSUE THREAD

**Issue by taufik-nurrohman** [mecha-cms/x.panel#23]
The `$state->x->panel->path` property just adds complexity. Since _panel_ relies on _user_, it would be simpler if we use the `$state->x->user->path` and `$state->x->user->guard->path` value as the namespace for _panel_ routes.

Currently, the route pattern contains a command stored as `/::command-name::/` in the URL. This pattern for sure makes it easy to instantly swap the commands by replacing the URL value using functions like `strtr()` and `str_replace()` due to its striking pattern. This pattern has been around since version `1.x.x` of the _panel_, but currently, such URL patterns got quite dirty and becomes more and more difficult to be served as dynamic route patterns as more features in the _panel_ grew.

Roughly speaking, I’d like to suggest a URL pattern for _panel_ version `3.x.x`, which is neater and will blends-in nicely with the front-end routes:

~~~ txt
./user → the log-in page
./user/taufik → the user page
~~~

~~~ txt
./panel/fire/asdf/page/lorem-ipsum.page → the panel path for “asdf” (custom) task
./panel/get/page/lorem-ipsum.page → the panel path for “edit” task
./panel/let/page/lorem-ipsum.page → the panel path for “delete” task
./panel/set/page → the panel path for “create” task
~~~

Both `/user` and `/panel` path will be stored in the same extension state storage (of the _user_ extension). `/user` will be stored in `$state->x->user->path` and `/panel` **_can_** be stored in `$state->x->user->guard->path`. Due to the nature of _user_ being independent from _panel_, the (secret) value of `$state->x->user->guard->path` don’t have to be assigned to _user_, so that by default, the `/panel` path will be returned as `/user`, since it was the default value for the secret user log-in path when that secret value is not set (as `/panel`, for example).

~~~ txt
./user/get/page/lorem-ipsum.page → the default panel path for “edit” task
./user/let/page/lorem-ipsum.page → the default panel path for “delete” task
./user/set/page → the default panel path for “create” task
~~~

~~~ php
$base = $state->x->user->guard->path ?? $state->x->user->path ?? '/user';

Route::set($base . '/fire/?/*', function($fn, $path) { … });

Route::set($base . '/get/*', function($path) { … });
Route::set($base . '/let/*', function($path) { … });
Route::set($base . '/set/*', function($path) { … });
~~~

### Others

Remove `$_['/']` property. We should consider to use custom pattern in URL string that later will be replaced by the correct base _panel_ URL. For example, we can use dummy URL protocol or fake relative URL which later will be replaced with `http://127.0.0.1/panel/?/` in the output:

~~~ txt
get://page/lorem-ipsum.page
let://page/lorem-ipsum.page
set://page/lorem-ipsum.page
~~~

~~~ txt
.../get/page/lorem-ipsum.page
~~~

~~~ txt
&/get/page/lorem-ipsum.page
~~~

Replace `$_['f']` property with `$_['source']`, which its value can be either file or folder path. Ideally, the most common property name to store a file/folder path in Mecha is “path”. But, it is already used to store URL parts after the folder name, along with `$_['hash']`, `$_['i']`, `$_['id']`, and `$_['query']` properties.

Alternatively, instead of removing `$_['/']`, we can rename it with `$_['root']` to follow Mecha’s standard URL properties. But this likely will change the `$_['path']` value, ideally, to also include the folder path. Which will make `$_['id']` property becomes useless. Later, `$_['root']` ideally should also include the `$_['task']` part, which will make `$_['task']` property becomes useless.

~~~ php
$_['ground'] // "http://127.0.0.1/panel"
$_['root'] // "http://127.0.0.1/panel/get"
$_['path'] // "page/lorem-ipsum.page"
$_['i'] // 1
$_['query'] // "foo=bar&baz=qux"
$_['hash'] // "foo"
~~~

~~~ php
// Detect current task
if (str_ends_with($_['root'], '/get')) { … }

// Detect current folder
if ('page' === $_['path'] || str_starts_with($_['path'], 'page/')) { … }
~~~

**Comment by taufik-nurrohman** [comment]
Or, to completely remove the task part in URL, and assign it to the query string instead.

~~~ txt
./panel/page → “edit” or “read” task by default
./panel/page?task=set&type=page/page → “create” task
./panel/page?task=let → “delete” task
~~~

The benefit is, you can run &ldquo;delete&rdquo; task using `POST` request.

~~~ html
<form method="post">
  <button name="task" type="submit" value="let">
    Delete
  </button>
</form>
~~~

**Comment by taufik-nurrohman** [comment]
What if I put the user name in URL too?

~~~ txt
./user/taufik-nurrohman/page → “edit” or “read” task by default
./user/taufik-nurrohman/page?task=set&type=page/page → “create” task
./user/taufik-nurrohman/page?task=let → “delete” task
~~~

**Comment by igoynawamreh** [comment]
> What if I put the user name in URL too? This will make it easier to validate current user.

How about removing `/user` in the URL?

**Comment by taufik-nurrohman** [comment]
> How about removing `/user` in the URL?

@igoynawamreh the reason why I want to keep the `/user` part is because _user_ extension has a secret log-in path feature. It&rsquo;s just that I don&rsquo;t have the time to document it. If you set a `path` property to the `guard` property with random value, that value will then becomes the log-in path:

~~~ php
return [
    'path' => '/user',
    'guard' => [
        'path' => '/panel'
    ]
];
~~~

From the states above, expect to have `http://127.0.0.1/user/taufik-nurrohman` as the user profile page, and `http://127.0.0.1/panel` as the log-in path.

**Comment by igoynawamreh** [comment]
If so then I agree to use username in the URL.

**Comment by igoynawamreh** [comment]
But for some web apps I prefer not to put the user in the URL.

What do you think?

**Comment by taufik-nurrohman** [comment]
What kind of web app is that?

You can always alias the route if you want:

~~~ php
Route::set('taufik-nurrohman', function() {
    // Probably put some conditional check here, to prevent
    // conflict with the existing static page URL.
    if ($file = File::exist(LOT . DS . 'taufik-nurrohman.page')) {
        // Load static page here!
    } else {
        Route::fire('user/:user', ['taufik-nurrohman']);
    }
});
~~~

**Comment by taufik-nurrohman** [comment]
Rethinking the root data. Probably, a `route` property is enough to store panel URL for testing purpose.

~~~ .yaml
asset: []
description: null
form:
  data: []
  lot: []
  type: null
hash: null
i: null
icon: []
lot: []
query: []
route: null
skin: []
source: null
task: null
type: null
~~~

**Comment by taufik-nurrohman** [comment]
~~~ php
if (str_ends_with($_['d'], '/get') && str_starts_with($_['type'] . '/', 'page/')) {
    // Is editing a page file and is in page editor mode
}
~~~

**Comment by taufik-nurrohman** [comment]
All data stored in `$_` variable must be primitive and can be easily encoded/decoded as JSON for easy transmission.
