### ISSUE TITLE
First try out of the box, doesn’t work. 

### ISSUE THREAD

**Issue by timothymarois** [mecha-cms/x.panel#8]
So far Ive only managed to get to the add user screen. When creating a user, no success says its completed (the user file is created in the directory) and then any pages in the header navigation all go to 404 pages of the default website template. apache is active, htaccess is running, Using under the same environment all my other php frameworks/cms's. But for whatever reason the panel of this cms extension does nothing at all. The default site pages work just fine. Am I missing some configuration setting?

**Comment by tovic** [comment]
I have just commited some files for about 10 minutes ago. Let me to check them first.

**Comment by tovic** [comment]
Done for now. I have tested it and can’t reproduce the bug. What is the generated `status` property in the user file you created?
